services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: vincebus-ftp-prod
    restart: always
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    networks:
      - vincebus-network

  db:
    image: postgres:14
    container_name: vincebus-ftp-db-prod
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - vincebus-network

networks:
  vincebus-network:
    driver: bridge

volumes:
  postgres_prod_data:
